### PR TITLE
backend/frontend/patches: Smalltalk patches automatically applied to Pharo

### LINKED ISSUE #48: Studio attempts to load shared libraries from /usr
When I press “play” I get thrown into the Debugger because Studio attempted to load a shared library from `/usr` instead of `/nix`. Below are the Debugger stack trace and the console output:

```
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
AthensCairoSurface class>>primImage:width:height:
FFICalloutAPI>>function:module:
AthensCairoSurface class(Object)>>nbCall:
AthensCairoSurface class>>primImage:width:height:
AthensCairoSurface class>>extent:format:
AthensCairoSurface class>>extent:
TRCanvas>>initialize
TRCanvas class(Behavior)>>new
RTView>>initialize
RTView class(Behavior)>>new
RTMondrian(RTBuilder)>>createView
RTMondrian>>createView
RTMondrian(RTBuilder)>>initialize
RTMondrian>>initialize
RTMondrian class(Behavior)>>new
RJITAuditLog>>visualizeMondrianOverview
RJITProcess>>gtInspectorJITIn:
[ :eachPragma | 
eachPragma methodSelector numArgs = 0
	ifTrue: [ | presentationSource |
		presentationSource := self perform: eachPragma selector.
		presentationSource glmPresentation
			cull: composite
			cull: aGTInspector
			cull: self ].
eachPragma methodSelector numArgs = 1
	ifTrue: [ thisContext
			object: self
			perform: eachPragma methodSelector
			withArguments: {composite}
			inClass: self class ].
eachPragma methodSelector numArgs = 2
	ifTrue: [ thisContext
			object: self
			perform: eachPragma methodSelector
			withArguments:
				{composite.
				aGTInspector}
			inClass: self class ] ] in RJITProcess(ProtoObject)>>gtInspectorPresentationsFromPragmas:In:inContext:
Array(SequenceableCollection)>>do:
RJITProcess(ProtoObject)>>gtInspectorPresentationsFromPragmas:In:inContext:
RJITProcess(ProtoObject)>>gtInspectorPresentationsIn:inContext:
[ :d | each gtInspectorPresentationsIn: d inContext: self ] in [ :x | 
(GLMCompositePresentation new
	with:
		[ :d | each gtInspectorPresentationsIn: d inContext: self ])
	startOn: x ] in [ :a :each | 
a title: [ self printObjectAsAnItem: each ].
a
	dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
a titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
a dynamic
	display: [ :x | 
		(GLMCompositePresentation new
			with:
				[ :d | each gtInspectorPresentationsIn: d inContext: self ])
			startOn: x ] ] in [ :browser | 
browser fixedSizePanes: self class numberOfInspectorPanes.
browser
	show: [ :a :each | 
		a title: [ self printObjectAsAnItem: each ].
		a
			dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
		a
			titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
		a dynamic
			display: [ :x | 
				(GLMCompositePresentation new
					with:
						[ :d | each gtInspectorPresentationsIn: d inContext: self ])
					startOn: x ] ] ] in StudioInspector(GTInspector)>>compose
GLMCompositePresentation(GLMPresentation)>>with:
[ :x | 
(GLMCompositePresentation new
	with:
		[ :d | each gtInspectorPresentationsIn: d inContext: self ])
	startOn: x ] in [ :a :each | 
a title: [ self printObjectAsAnItem: each ].
a
	dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
a titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
a dynamic
	display: [ :x | 
		(GLMCompositePresentation new
			with:
				[ :d | each gtInspectorPresentationsIn: d inContext: self ])
			startOn: x ] ] in [ :browser | 
browser fixedSizePanes: self class numberOfInspectorPanes.
browser
	show: [ :a :each | 
		a title: [ self printObjectAsAnItem: each ].
		a
			dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
		a
			titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
		a dynamic
			display: [ :x | 
				(GLMCompositePresentation new
					with:
						[ :d | each gtInspectorPresentationsIn: d inContext: self ])
					startOn: x ] ] ] in StudioInspector(GTInspector)>>compose
BlockClosure>>glamourValueWithArgs:
BlockClosure(ProtoObject)>>glamourValue:
GLMDynamicPresentation(GLMPresentation)>>displayValue
GLMDynamicPresentation>>currentPresentation
GLMMorphicDynamicRenderer>>render:
GLMMorphicDynamicRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderDynamicPresentation:
GLMDynamicPresentation>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderWithTitleOrNil:
GLMMorphicTabbedRenderer>>render:
GLMMorphicTabbedRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderTabbedCompositePresentation:
GLMTabbedArrangement>>renderGlamorouslyOn:
GLMCompositePresentation>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicPaneRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicPaneRenderer>>renderContainerFor:
GLMMorphicPaneRenderer>>render:
GLMMorphicPaneRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderPane:
GLMPane>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicPagerRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicPagerRenderer>>actOnPaneAdded:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver:
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt:
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
GLMPager(Announcer)>>announce:
GLMPager(GLMAnnouncer)>>announce:
GLMPager(GLMLoggedObject)>>announce:
GLMPager(GLMFinder)>>innerPortEvent:
GLMPane>>portEvent:
[ self silentValue: anObject.
self pane
	portEvent:
		(GLMPortEvent
			on: self
			previouslyValued: oldValue
			in: aTransmissionContext) ] in GLMPanePort>>changeValueTo:in:
GLMPane>>notingPresentationChangeDo:
GLMPanePort>>changeValueTo:in:
GLMPanePort>>value:in:
GLMPanePort(GLMPort)>>value:
GLMPortUpdater>>glamourValueWithArgs:
GLMGenericAction(GLMAction)>>actOn:
GLMGenericAction(GLMAction)>>morphicActOn:
GLMPluggableButtonMorph(PluggableButtonMorph)>>performAction:
[ :m | 
(m containsPoint: evt cursorPoint)
	ifTrue: [ m enabled
			ifTrue: [ m performAction: evt ] ] ] in GLMPluggableButtonMorph(PluggableButtonMorph)>>mouseUp:
Array(SequenceableCollection)>>do:
GLMPluggableButtonMorph(PluggableButtonMorph)>>mouseUp:
GLMPluggableButtonMorph(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
GLMPluggableButtonMorph(Morph)>>handleEvent:
GLMPluggableButtonMorph(Morph)>>handleFocusEvent:
[ ActiveHand := self.
ActiveEvent := anEvent.
result := focusHolder
	handleFocusEvent: (anEvent transformedBy: (focusHolder transformedFrom: self)) ] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>on:do:
WorldMorph(PasteUpMorph)>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
HandMorph>>processEventsFromQueue:
HandMorph>>processEvents
[ :h | 
self activeHand: h.
h processEvents.
self activeHand: nil ] in WorldState>>doOneCycleNowFor:
Array(SequenceableCollection)>>do:
WorldState>>handsDo:
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess
```

```
% studio-x11
setlocale() failed (check values of LC_CTYPE, LANG and LC_ALL)
pthread_setschedparam failed: Operation not permitted
ioLoadModule(//usr/lib/libcairo.so.2):
  libpixman-1.so.0: cannot open shared object file: No such file or directory
Error: External module not found
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
AthensCairoSurface class>>primImage:width:height:
FFICalloutAPI>>function:module:
AthensCairoSurface class(Object)>>nbCall:
AthensCairoSurface class>>primImage:width:height:
AthensCairoSurface class>>extent:format:
AthensCairoSurface class>>extent:
TRCanvas>>initialize
TRCanvas class(Behavior)>>new
RTView>>initialize
RTView class(Behavior)>>new
RTMondrian(RTBuilder)>>createView
RTMondrian>>createView
RTMondrian(RTBuilder)>>initialize
RTMondrian>>initialize
RTMondrian class(Behavior)>>new
RJITAuditLog>>visualizeMondrianOverview
RJITProcess>>gtInspectorJITIn:
[ :eachPragma | 
eachPragma methodSelector numArgs = 0
	ifTrue: [ | presentationSource |
		presentationSource := self perform: eachPragma selector.
		presentationSource glmPresentation
			cull: composite
			cull: aGTInspector
			cull: self ].
eachPragma methodSelector numArgs = 1
	ifTrue: [ thisContext
			object: self
			perform: eachPragma methodSelector
			withArguments: {composite}
			inClass: self class ].
eachPragma methodSelector numArgs = 2
	ifTrue: [ thisContext
			object: self
			perform: eachPragma methodSelector
			withArguments:
				{composite.
				aGTInspector}
			inClass: self class ] ] in RJITProcess(ProtoObject)>>gtInspectorPresentationsFromPragmas:In:inContext: in Block: [ :eachPragma | ...
Array(SequenceableCollection)>>do:
RJITProcess(ProtoObject)>>gtInspectorPresentationsFromPragmas:In:inContext:
RJITProcess(ProtoObject)>>gtInspectorPresentationsIn:inContext:
[ :d | each gtInspectorPresentationsIn: d inContext: self ] in [ :x | 
(GLMCompositePresentation new
	with:
		[ :d | each gtInspectorPresentationsIn: d inContext: self ])
	startOn: x ] in [ :a :each | 
a title: [ self printObjectAsAnItem: each ].
a
	dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
a titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
a dynamic
	display: [ :x | 
		(GLMCompositePresentation new
			with:
				[ :d | each gtInspectorPresentationsIn: d inContext: self ])
			startOn: x ] ] in [ :browser | 
browser fixedSizePanes: self class numberOfInspectorPanes.
browser
	show: [ :a :each | 
		a title: [ self printObjectAsAnItem: each ].
		a
			dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
		a
			titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
		a dynamic
			display: [ :x | 
				(GLMCompositePresentation new
					with:
						[ :d | each gtInspectorPresentationsIn: d inContext: self ])
					startOn: x ] ] ] in StudioInspector(GTInspector)>>compose in Block: [ :d | each gtInspectorPresentationsIn: d inContex...etc...
GLMCompositePresentation(GLMPresentation)>>with:
[ :x | 
(GLMCompositePresentation new
	with:
		[ :d | each gtInspectorPresentationsIn: d inContext: self ])
	startOn: x ] in [ :a :each | 
a title: [ self printObjectAsAnItem: each ].
a
	dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
a titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
a dynamic
	display: [ :x | 
		(GLMCompositePresentation new
			with:
				[ :d | each gtInspectorPresentationsIn: d inContext: self ])
			startOn: x ] ] in [ :browser | 
browser fixedSizePanes: self class numberOfInspectorPanes.
browser
	show: [ :a :each | 
		a title: [ self printObjectAsAnItem: each ].
		a
			dynamicActions: [ :aPresentation | each gtInspectorActions asOrderedCollection ].
		a
			titleAction: [ :aPresentation | self closeActionFor: aPresentation ].
		a dynamic
			display: [ :x | 
				(GLMCompositePresentation new
					with:
						[ :d | each gtInspectorPresentationsIn: d inContext: self ])
					startOn: x ] ] ] in StudioInspector(GTInspector)>>compose in Block: [ :x | ...
BlockClosure>>glamourValueWithArgs:
BlockClosure(ProtoObject)>>glamourValue:
GLMDynamicPresentation(GLMPresentation)>>displayValue
```

### PR DESCRIPTION
**Pull request by lukego**
Currently populated with CairoStrictLibraryPath.cs that is intended to resolve #48.

### CODE REVIEW

**Comment by lukego** [comment]
Here is a screenshot of the patch (hah):

screenshot 2018-01-19 13 35 10

The intention is to only look for libcairo in `LD_LIBRARY_PATH` without checking for any hard-coded places. Does `strace` show that Pharo is still looking in those paths? If so then perhaps the patch has not applied successfully.

You should be able to check the log to see if the image was patched:

```
git/studo$ nix-store --read-log $(nix-instantiate -E '(import ./.).studio-image')
...
Patching: /nix/store/lms9m50axd506hfwpk0m19db7bkg44dy-patches/CairoStrictLibraryPath.cs
```

I suppose the issue could otherwise be that your `LD_LIBRARY_PATH` is pointing to those directories and this is visible to Pharo. In that case perhaps adding `--pure` to `nix-shell` would help by sanitizing your shell environment before Studio starts?

**Comment by lukego** [comment]
(are you running Studio with `bin/studio`? If so then it should always build the latest image from your source tree before starting. If you are running an older version installed in your path with `studio-vnc` then it could be stale.)

**Comment by eugeneia** [comment]
Its not looking at `/nix/store/*pixman*` at all, so maybe a missing dependency declaration? I tried

```
diff --git a/backend/frontend/default.nix b/backend/frontend/default.nix
index 3e82bf3..d8c4fa2 100644
--- a/backend/frontend/default.nix
+++ b/backend/frontend/default.nix
@@ -150,7 +150,7 @@ in
   
 {
   # main package collection for 'nix-env -i'
-  studio = { inherit studio-x11 studio-vnc tigervnc; };
+  studio = { inherit studio-x11 studio-vnc tigervnc pixman; };
   # individual packages
   studio-gui = studio-x11;           # deprecated
   studio-gui-vnc = studio-vnc;       # deprecated
```

…but that doesn’t do anything.

**Comment by lukego** [comment]
@eugeneia Hm. Could be missing libraries. I wonder if running `nix-shell --pure` on my machine would reproduce the problem so that it doesn't find them.

Anyway: The idea is that a shell script starts the Pharo VM with an `LD_LIBRARY_PATH` that specifies all the libraries it should use at runtime. That code is here: https://github.com/studio/studio/blob/master/backend/pharo/vm/default.nix#L87.

**Comment by eugeneia** [comment]
Something is awry here: (On master) I updated the pharo nix expression to include the missing dependency…

```
modified   backend/pharo/vm/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchurl, fetchFromGitHub, bash, unzip, glibc, openssl, gcc, mesa, freetype, xorg, alsaLib, cairo, libuuid, autoreconfHook, gcc48, runCommand, ... }:
+{ stdenv, fetchurl, fetchFromGitHub, bash, unzip, glibc, openssl, gcc, mesa, freetype, xorg, alsaLib, cairo, pixman, libuuid, autoreconfHook, gcc48, runCommand, ... }:
 
 # Build the Pharo VM
 stdenv.mkDerivation rec {
@@ -84,7 +84,7 @@ stdenv.mkDerivation rec {
     mkdir -p "$out/bin"
 
     # Note: include ELF rpath in LD_LIBRARY_PATH for finding libc.
-    libs=$out:$(patchelf --print-rpath "$out/pharo"):${cairo}/lib:${mesa}/lib:${freetype}/lib:${openssl}/lib:${libuuid}/lib:${alsaLib}/lib:${xorg.libICE}/lib:${xorg.libSM}/lib
+    libs=$out:$(patchelf --print-rpath "$out/pharo"):${cairo}/lib:${pixman}/lib:${mesa}/lib:${freetype}/lib:${openssl}/lib:${libuuid}/lib:${alsaLib}/lib:${xorg.libICE}/lib:${xorg.libSM}/lib
 
     # Create the script
     cat > "$out/bin/pharo" <<EOF
@@ -104,5 +104,5 @@ stdenv.mkDerivation rec {
   # http://forum.world.st/OSProcess-fork-issue-with-Debian-built-VM-td4947326.html
   #
   # (stack protection is disabled above for gcc 4.8 compatibility.)
-  nativeBuildInputs = [ bash unzip glibc openssl gcc48 mesa freetype xorg.libX11 xorg.libICE xorg.libSM alsaLib cairo pharo-share libuuid autoreconfHook ];
+  nativeBuildInputs = [ bash unzip glibc openssl gcc48 mesa freetype xorg.libX11 xorg.libICE xorg.libSM alsaLib cairo pixman pharo-share libuuid autoreconfHook ];
 }
```

…but `bin/studio x11` wouldn’t pick up the changes, instead if would run a sttale version that I had lying in `/nix/store`. So I went nuclear and did a `sudo rm -rf /nix && rm -rf ~/.nix-*` and started fresh, and now I get the following when running `bin/studio x11`:

```
→ bin/studio x11
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_COLLATE = "C",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/tmp/nix-shell.erdfMt/rc: line 1: studio-x11: command not found
```

**Comment by eugeneia** [comment]
Ok, I needed #62. My changes fix the missing dependency and now I run into the next unmet dependency (`fontconfig`). I can again confirm my suspicions that `bin/studio` is broken in the way that it won’t pick up my changes to `backend/pharo/vm/default.nix`, again.

I can work around this via `nix-collect-garbage -d` (that didn’t suffice previously because I had installed studio initially via `nix-env -i`). Not exactly fast iteration times, though. ;-)

So the bug here is rather, that it works on your system. I.e. if the patch would work, you should run into the same errors I am seeing?

**Pull request merged**
